"""Auto-generate map_methods_summary.txt — exact formulas, thresholds, year
window, caps, and per-region data coverage used to produce the published figure.

This file is meant to be pasted (with light editing) into the SI methods.
"""
from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from _config import (  # noqa: E402
    DIR_PROCESSED,
    EXPOSURE_HIGH,
    EXPOSURE_LOW,
    EXPOSURE_W_INTENSITY,
    EXPOSURE_W_RELIANCE,
    HIGH_INTENSITY_KG_HA,
    HIGH_RELIANCE,
    LOW_INTENSITY_KG_HA,
    LOW_RELIANCE,
    MATERIAL_STAKE_KG_HA,
    N_INTENSITY_CAP,
    REEXPORT_AC_FLOOR_T,
    REEXPORT_RATIO_FLAG,
    REEXPORT_TRADE_FLOOR_T,
    STAKE_FLOOR_SENSITIVITY,
    YEAR_END,
    YEAR_LABEL,
    YEAR_START,
)


def main() -> int:
    vul = pd.read_csv(DIR_PROCESSED / "vulnerability_country.csv")
    sens = pd.read_csv(DIR_PROCESSED / "threshold_sensitivity_summary.csv")

    eligible = vul["buffer_proxy_t_ha"].notna() & (vul["cropland_Mha"] >= 0.1)
    bcuts = vul.loc[eligible, "buffer_proxy_t_ha"].quantile([1/3, 2/3]).values

    composition = (vul.groupby("panel_c_class")["cropland_Mha"].sum()
                      .sort_values(ascending=False))
    total = composition.sum()

    lines = []
    p = lines.append
    p(f"# Figure 4 — Methods summary (auto-generated {dt.date.today():%Y-%m-%d})")
    p("")
    p("This file is auto-generated by scripts/11_methods_summary.py from the")
    p("processed data files. Every value below traces to a CSV in")
    p("data_processed/.")
    p("")
    p("## Year window")
    p(f"  All FAOSTAT layers averaged over {YEAR_START}–{YEAR_END} ({YEAR_LABEL}).")
    p("  Soil layers (SoilGrids 2.0 v2.0.0) are time-invariant within this")
    p("  analytical window.")
    p("")
    p("## Buffer proxy (panel a / country buffer side)")
    p("  Source: SoilGrids 2.0 5 km aggregated rasters (Homolosine, ESRI:54052)")
    p("    - ocs_0-30cm_mean   (SOC stock 0–30 cm; t C / ha)")
    p("    - nitrogen 0-5, 5-15, 15-30 cm (cg/kg → ÷100 → g/kg)")
    p("    - bdod     0-5, 5-15, 15-30 cm (cg/cm³ → ÷100 → g/cm³)")
    p("")
    p("  Total N stock 0–30 cm computed by integration over depth slabs:")
    p("    N_stock_slab [t N/ha] = N_conc [g/kg] × BD [g/cm³] × thickness [m] × 10")
    p("")
    p("  Country aggregation: PHASE 2 LOCKED — cropland-weighted mean.")
    p("    Weights: MIRCA2000 maximum total annual cropped area (Portmann et al.")
    p("    2010; Zenodo 7422506). 5 arcmin (~9 km) ESRI-ASCII grid resampled to")
    p("    SoilGrids 5 km Homolosine via rasterio Resampling.sum.")
    p("    buffer_country_cwm = Σ(buffer × cropped_area) / Σ(cropped_area)")
    p("  Phase 1 (median, all-land) values retained in buffer_country.csv as")
    p("  cross-check fields with `_allland_` suffix.")
    p("")
    p("  Buffer proxy = country-cropland-weighted-mean total N stock 0–30 cm")
    p("               (mathematically equal to SOC_stock / C:N within cropland)")
    p("")
    p(f"  Pre-specified terciles within cropland-bearing countries (≥ 100,000 ha):")
    p(f"    Low   buffer: < {bcuts[0]:.2f} t N/ha")
    p(f"    High  buffer: ≥ {bcuts[1]:.2f} t N/ha")
    p(f"    countries entering tercile calculation: {int(eligible.sum())}")
    p("")
    p("## Exposure (panel b / country exposure side)")
    p("  Sources: FAOSTAT bulk CSVs")
    p("    - Inputs / Fertilizers by Nutrient (Item: Nutrient nitrogen N (total);")
    p("      Elements: Agricultural Use, Production, Import quantity,")
    p("                Export quantity)")
    p("    - Inputs / Land Use (Item: Cropland; Element: Area; unit 1000 ha)")
    p("")
    p("  Sub-index 1 — Synthetic N application intensity:")
    p("    N_intensity_raw    = N_use_t × 1000 / cropland_ha   [kg N / ha]")
    p(f"    N_intensity_scaled = min(N_intensity_raw, {N_INTENSITY_CAP:.0f}) "
      f"/ {N_INTENSITY_CAP:.0f}   [0–1]")
    p("")
    p("  Sub-index 2 — Net N-fertilizer import reliance:")
    p("    Apparent_consumption = Production + Imports − Exports   [t N]")
    p("    Net_imports          = max(0, Imports − Exports)        [t N]")
    p("    Import_reliance      = clip(Net_imports / Apparent_consumption, 0, 1)")
    p("")
    p(f"  Combined index (kept for SI cross-check only):")
    p(f"    Exposure = {EXPOSURE_W_INTENSITY:.1f}×N_intensity_scaled "
      f"+ {EXPOSURE_W_RELIANCE:.1f}×Import_reliance")
    p("")
    p("## Exposure classification — LOCKED Modified Two-Pathway Max-Rule")
    p("  HIGH if either pathway holds:")
    p(f"    (A) input-intensity     : N_intensity_raw ≥ {HIGH_INTENSITY_KG_HA:.0f} kg N/ha")
    p(f"    (B) import-dependence   : Import_reliance ≥ {HIGH_RELIANCE:.2f} "
      f"AND N_intensity_raw ≥ {MATERIAL_STAKE_KG_HA:.0f} kg N/ha")
    p(f"  LOW  if N_intensity_raw < {LOW_INTENSITY_KG_HA:.0f} "
      f"AND Import_reliance < {LOW_RELIANCE:.2f}")
    p("  MODERATE: everything else")
    p("  DATA_MISSING: intensity or reliance unavailable")
    p("")
    p("## Re-export hub flag (tightened, not a classification)")
    p(f"  All three must hold:")
    p(f"    (Imports + Exports) / Apparent_consumption > {REEXPORT_RATIO_FLAG:.0f}")
    p(f"    Imports + Exports > {REEXPORT_TRADE_FLOOR_T:.0f} t N")
    p(f"    Apparent_consumption > {REEXPORT_AC_FLOOR_T:.0f} t N")
    p("  Treatment: flagged in data table + caption footnote; no map hatching.")
    p("")
    p("## Panel c — Combined buffer × exposure classification (5 classes + missing)")
    p("  Class assignments:")
    p("    high buffer  × low  exposure  → 'High buffer / low exposure'")
    p("    high buffer  × high exposure  → 'High buffer / high exposure'")
    p("    low  buffer  × low  exposure  → 'Low buffer / low exposure'")
    p("    low  buffer  × high exposure  → 'Low buffer / high exposure'  (focal)")
    p("    any moderate component        → 'Intermediate'")
    p("    missing input                 → 'Data missing'")
    p("")
    p("## Final composition (cropland-area-weighted)")
    for cls, v in composition.items():
        p(f"    {cls:30s}  {v:8.1f} Mha   {100*v/total:5.1f} %")
    p("")
    p("## Stake-floor sensitivity (focal-class cropland share)")
    for stake in STAKE_FLOOR_SENSITIVITY:
        row = sens[sens.index.astype(str) == ""]  # placeholder
    sens2 = pd.read_csv(DIR_PROCESSED / "threshold_sensitivity_summary.csv")
    sens2 = sens2.rename(columns={sens2.columns[0]: "rule"})
    sens2 = sens2.set_index("rule")
    p("    Rule                                          focal-class %")
    for rule_name in sens2.index:
        focal = sens2.loc[rule_name, "low_buffer_high_exposure"]
        p(f"    {rule_name:45s}  {focal:>5.1f} %")
    p("")
    p("## Scope statement (must appear in main text and SI)")
    p("  This figure maps a mechanism-specific resilience screen. It does not")
    p("  include poverty, irrigation, crop mix, conflict, fiscal capacity,")
    p("  food-import dependence, or adaptive policy response, and should not")
    p("  be interpreted as a food-security vulnerability index.")
    p("")
    p("## Phase 2 limitations (remaining)")
    p("  1. Panel a is a country-level cropland-weighted choropleth, not a")
    p("     pixel-level cropland raster. Pixel-level panel a would require")
    p("     SoilGrids 250 m tile mosaic + cropland mask (~5 GB). Country-level")
    p("     panel a is publication-grade for the figure's altitude.")
    p("  2. MIRCA2000 cropped-area weights are circa 2000. Newer 5 arcmin")
    p("     cropland products (e.g., MIRCA-OS, ESA WorldCover) could be used")
    p("     in a future revision; for now, MIRCA is openly available without")
    p("     registration and gives reasonable cropland weights. Cropland")
    p("     extent has shifted somewhat 2000→2020 (esp. tropical expansion).")
    p("  3. N intensity uses cropland denominator, while FAOSTAT 'Agricultural")
    p("     Use' includes fertilizer applied to permanent pasture. Pasture-")
    p("     heavy countries (Ireland, NZ, UK, Australia) get inflated raw")
    p("     intensity; the 300 kg/ha cap absorbs the worst cases. SI should")
    p("     report sensitivity using Cropland + Permanent meadows as the")
    p("     denominator.")
    p("")

    out = DIR_PROCESSED / "map_methods_summary.txt"
    out.write_text("\n".join(lines))
    print(f"  wrote {out}")
    print()
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
