#!/usr/bin/env python3
"""Score the claim register and deposit its baselines and report.

Spec: FINDINGS.md F-012, F-015, F-016. Rebuilt by WP5 on 2026-07-26.

Writes
    docs/claims_baseline.json         the frozen drifted set and the owed count
    docs/claims_index_baseline.json   the frozen claim/parameter two-way index
    results/claims_report.md          the human-readable scoring
    outputs/claims_status.csv         one row per check, for the SI table

This is a generator, not a test. `code/tests/test_claims.py` scores the same
register through the same resolver and fails the build; this writes the
artifacts. The SI has to print the table, and a generator that imported a test
would rebuild the one-concept-two-places failure the rebuild is about.

    python3 code/repro/make_claim_report.py            # report only
    python3 code/repro/make_claim_report.py --freeze   # also rewrite the baselines

`--freeze` is deliberately not the default. A baseline that regenerates itself
on every run cannot catch a number that got better silently, which is the whole
point of having one.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from typing import Any, Dict, List, Mapping

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))
sys.path.insert(0, os.path.join(REPO, "code", "model"))

import claim_resolvers as cr  # noqa: E402

DOCS = os.path.join(REPO, "docs")
RESULTS = os.path.join(REPO, "results")
OUTPUTS = os.path.join(REPO, "outputs")


def build_index(doc: Mapping[str, Any]) -> Dict[str, List[str]]:
    return {
        c["id"]: sorted(c.get("depends_on_params") or [])
        for c in doc["claims"]
        if c.get("depends_on_params")
    }


def write_baseline(doc: Mapping[str, Any], scoring: Mapping[str, Any]) -> None:
    """Freeze the drifted set, the drifted claims and the owed count.

    `owed_count` reads `status`, and only `status`. F-016 found C-010 carrying an
    `owed:` note while its status said `current`, so nothing counted it; the gate
    now refuses that shape outright rather than relying on this counter to notice.
    """
    os.makedirs(DOCS, exist_ok=True)
    payload = {
        "generated_by": "code/repro/make_claim_report.py --freeze",
        "spec": ["F-012", "F-015", "F-016"],
        "rule": (
            "This list may only shrink. A check that comes into line without this "
            "file being regenerated fails the build, and regenerating it requires an "
            "entry in FINDINGS.md saying why."
        ),
        "register_version": doc.get("register_version"),
        "n_claims": scoring["n_claims"],
        "n_checks": scoring["n_checks"],
        "n_agrees": scoring["n_agrees"],
        "n_drifted": scoring["n_drifted"],
        "drifted_claims": scoring["drifted_claims"],
        "drifted_checks": sorted(
            f"{r['claim']}/{r['check']}" for r in scoring["checks"] if r["verdict"] == "DRIFTED"
        ),
        "owed_generators": scoring["owed_generators"],
        "owed_count": scoring["owed_count"],
    }
    with open(os.path.join(DOCS, "claims_baseline.json"), "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=False)
        fh.write("\n")

    index = {
        "generated_by": "code/repro/make_claim_report.py --freeze",
        "spec": ["F-012"],
        "rule": (
            "The reverse index of affects_claims in params.yaml. Frozen so that a "
            "documentation edit which changes which published sentences a parameter "
            "is known to touch cannot land unremarked."
        ),
        "index": build_index(doc),
    }
    with open(os.path.join(DOCS, "claims_index_baseline.json"), "w", encoding="utf-8") as fh:
        json.dump(index, fh, indent=2, sort_keys=True)
        fh.write("\n")


def write_report(doc: Mapping[str, Any], scoring: Mapping[str, Any]) -> None:
    os.makedirs(RESULTS, exist_ok=True)
    os.makedirs(OUTPUTS, exist_ok=True)

    by_claim: Dict[str, List[Dict[str, Any]]] = {}
    for r in scoring["checks"]:
        by_claim.setdefault(r["claim"], []).append(r)

    lines: List[str] = []
    lines.append("# Claim register — scoring\n")
    lines.append(
        "Generated by `code/repro/make_claim_report.py`. Register "
        f"`docs/claims.yaml` ({doc.get('register_version')}), document basis "
        f"`{doc.get('document_basis')}`.\n"
    )
    lines.append(
        f"**{scoring['n_claims']} claims, {scoring['n_checks']} checks, "
        f"{scoring['n_agrees']} agreeing, {scoring['n_drifted']} drifted, "
        f"0 unresolved, {scoring['owed_count']} owed generators.**\n"
    )
    lines.append(
        "Drifted claims: " + ", ".join(f"`{c}`" for c in scoring["drifted_claims"]) + ".\n"
    )
    lines.append(
        "Every drift is an edit owed to the document, not a tolerance artefact. "
        "Tolerances come from each sentence's own stated precision and may not be "
        "widened to make a claim agree.\n"
    )

    for claim in doc["claims"]:
        cid = claim["id"]
        rows = by_claim.get(cid, [])
        n_d = sum(1 for r in rows if r["verdict"] == "DRIFTED")
        head = f"## {cid} — {claim['location']}"
        if n_d:
            head += f"  ({n_d} of {len(rows)} drifted)"
        lines.append(head + "\n")
        lines.append("> " + " ".join(str(claim["text"]).split()) + "\n")
        lines.append("| check | stated | model | delta | tol | verdict |")
        lines.append("|---|---:|---:|---:|---:|---|")
        for r in rows:
            lines.append(
                f"| `{r['check']}` | {r['stated']:g} | {r['model']:.4f} | "
                f"{r['delta']:+.4f} | {r['tol']:g} | {r['verdict']} |"
            )
        lines.append("")
        if claim.get("document_edit_owed"):
            lines.append(
                "**Document edit owed.** "
                + " ".join(str(claim["document_edit_owed"]).split())
                + "\n"
            )

    with open(os.path.join(RESULTS, "claims_report.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    with open(os.path.join(OUTPUTS, "claims_status.csv"), "w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(
            ["claim_id", "location", "check_id", "stated", "model", "delta", "tol", "units", "verdict"]
        )
        loc = {c["id"]: c["location"] for c in doc["claims"]}
        for r in scoring["checks"]:
            w.writerow(
                [
                    r["claim"],
                    loc[r["claim"]],
                    r["check"],
                    f"{r['stated']:g}",
                    f"{r['model']:.6f}",
                    f"{r['delta']:+.6f}",
                    f"{r['tol']:g}",
                    r["units"],
                    r["verdict"],
                ]
            )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--freeze", action="store_true", help="rewrite the two baseline JSONs")
    args = ap.parse_args()

    doc = cr.load_claims()
    scoring = cr.evaluate(doc)
    write_report(doc, scoring)
    if args.freeze:
        write_baseline(doc, scoring)

    print(
        "%d claims, %d checks, %d AGREES, %d DRIFTED, owed %d%s"
        % (
            scoring["n_claims"],
            scoring["n_checks"],
            scoring["n_agrees"],
            scoring["n_drifted"],
            scoring["owed_count"],
            "  (baselines rewritten)" if args.freeze else "",
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
